### ISSUE TITLE
destination for the CRD

### ISSUE THREAD

**Issue by Lautreck** [aws-samples/eks-nonintrusive-automated-ipmgmt-multus-pods#2]
Hello,
i don't understand in the CRD what is the (dst) destination is supposed to be.
I want to apply this service to this tutorial : https://github.com/aws-samples/eks-install-guide-for-multus/blob/main/cfn/templates/nodegroup/README.md

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-multus
  namespace: multus
  
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l2", 
      "ipam": {
        "type": "whereabouts",
        "datastore": "kubernetes",
        "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
        "range": "10.10.1.80-10.10.1.82/24",
        "routes": [
            **{ "dst": "10.10.10.48/32" }**  #where does this go???#whats is it? is it the worker? the router?
          ],
        "log_file" : "/tmp/whereabouts.log",
        "log_level" : "debug",
        "gateway": "10.10.1.1"
      }
    }'

**Comment by raghs-aws** [comment]
This dst is the destination route. basically in this example it says that for this i/f if you need to reach to 10.10.10.48/32 , then use the next hop (gateway) as 10.10.1.1
